In [1]:
import numpy as np
import pandas as pd
from sympy import symbols, solve
import sympy
import timeit

In [ ]:
# Домашняя работа №4.1

In [2]:
A = np.array([[2,-4],
     [3,5],
     [-1,0]])
B = np.array([[1,2,7],
     [-3,-4,0],
     [5,2,1]])
C = np.array([[6,-3,9],
     [4,-5,2],
     [8,1,5]])

AT = A.transpose()
BT = B.transpose()
ATC = AT.dot(C)
ATBT = AT.dot(BT)
D = ATC - 2 * ATBT

print(f"AT = {AT}")
print(f"BT = {BT}")
print(f"ATC = {ATC}")
print(f"D1 = {ATBT}")
print(f"D = {D}")

AT = [[ 2  3 -1]
 [-4  5  0]]
BT = [[ 1 -3  5]
 [ 2 -4  2]
 [ 7  0  1]]
ATC = [[ 16 -22  19]
 [ -4 -13 -26]]
D1 = [[  1 -18  15]
 [  6  -8 -10]]
D = [[ 14  14 -11]
 [-16   3  -6]]


In [ ]:
# Домашняя работа №4.2

In [3]:
start_a = timeit.default_timer()
A2 = np.array([[np.nan,2,3],[-1,np.nan,4]])
B2 = np.array([[1,2,-5],[2,-6,np.nan]])
C2 = np.array([[8,np.nan,-1],[1,6,4]])

print(f"x = {(C2-2*B2)[0,0]/3}")
print(f"y = {(C2-2*B2)[1,1]/3}")
print(f"z = {(C2-3*A2)[1,2]/2}")
print(f"u = {(3*A2+2*B2)[0,1]}")
stop_a = timeit.default_timer()

start_b = timeit.default_timer()
x,y,z,u = symbols('x y z u')
A=[[x,2,3],[-1,y,4]]
B=[[1,2,-5],[2,-6,z]]
C=[[8,u,-1],[1,6,4]]

eq1 = 3*A[0][0] + 2*B[0][0] - C[0][0]
eq2 = 3*A[0][1] + 2*B[0][1] - C[0][1]
eq3 = 3*A[1][1] + 2*B[1][1] - C[1][1]
eq4 = 3*A[1][2] + 2*B[1][2] - C[1][2]
sol = solve((eq1, eq2, eq3, eq4), (x,y,z,u))

print(sol)
stop_b = timeit.default_timer()

print(f"time_a - {stop_a-start_a:.7f}")
print(f"time_b - {stop_b-start_b:.7f}")

x = 2.0
y = 6.0
z = -4.0
u = 10.0
{x: 2, u: 10, y: 6, z: -4}
time_a - 0.0009137
time_b - 0.1097148
